apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: consolidation-service
  namespace: wms-platform
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: consolidation-service
