apiVersion: v1
kind: Service
metadata:
  name: consolidation-service
  namespace: wms-platform
  labels:
    app: consolidation-service
    tier: backend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8005
    targetPort: http
    protocol: TCP
  - name: grpc
    port: 9005
    targetPort: grpc
    protocol: TCP
  selector:
    app: consolidation-service
