apiVersion: v1
kind: Service
metadata:
  name: routing-service
  namespace: wms-platform
  labels:
    app: routing-service
    tier: backend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8003
    targetPort: http
    protocol: TCP
  - name: grpc
    port: 9003
    targetPort: grpc
    protocol: TCP
  selector:
    app: routing-service
