apiVersion: v1
kind: Service
metadata:
  name: waving-service
  namespace: wms-platform
  labels:
    app: waving-service
    tier: backend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8002
    targetPort: http
    protocol: TCP
  - name: grpc
    port: 9002
    targetPort: grpc
    protocol: TCP
  selector:
    app: waving-service
