apiVersion: v1
kind: Service
metadata:
  name: facility-service
  namespace: wms-platform
  labels:
    app: facility-service
    tier: backend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8010
    targetPort: http
    protocol: TCP
  - name: grpc
    port: 9010
    targetPort: grpc
    protocol: TCP
  selector:
    app: facility-service
