{{- if .Values.platformConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app: wms-platform
    {{- include "wms-platform.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.platformConfig.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
