{{- if .Values.mongodb.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongodb.secretName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "wms-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  uri: {{ .Values.mongodb.uri | quote }}
{{- end }}
