apiVersion: v1
kind: Service
metadata:
  name: labor-service
  namespace: wms-platform
  labels:
    app: labor-service
    tier: backend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8009
    targetPort: http
    protocol: TCP
  - name: grpc
    port: 9009
    targetPort: grpc
    protocol: TCP
  selector:
    app: labor-service
