apiVersion: v1
kind: Service
metadata:
  name: packing-service
  namespace: wms-platform
  labels:
    app: packing-service
    tier: backend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8006
    targetPort: http
    protocol: TCP
  - name: grpc
    port: 9006
    targetPort: grpc
    protocol: TCP
  selector:
    app: packing-service
