apiVersion: v1
kind: Service
metadata:
  name: picking-service
  namespace: wms-platform
  labels:
    app: picking-service
    tier: backend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8004
    targetPort: http
    protocol: TCP
  - name: grpc
    port: 9004
    targetPort: grpc
    protocol: TCP
  selector:
    app: picking-service
