apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  namespace: wms-platform
  labels:
    app: shipping-service
    tier: backend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8007
    targetPort: http
    protocol: TCP
  - name: grpc
    port: 9007
    targetPort: grpc
    protocol: TCP
  selector:
    app: shipping-service
