apiVersion: v1
kind: ServiceAccount
metadata:
  name: wms-platform
  namespace: wms-platform
  labels:
    app: wms-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wms-platform
  namespace: wms-platform
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wms-platform
  namespace: wms-platform
subjects:
- kind: ServiceAccount
  name: wms-platform
  namespace: wms-platform
roleRef:
  kind: Role
  name: wms-platform
  apiGroup: rbac.authorization.k8s.io
